## numpy 와 닮은 파이토치 (pytorch)

1.   항목 추가
2.   항목 추가



In [2]:
import torch
a=torch.tensor([1,2,3,4])
print(a)
print(type(a))
print(a.dtype) # data type
print(a.shape)
print(a)
b=torch.tensor([1,2, 3.1   , 4])
print(b.dtype) # 하나라도 실수면 자동으로 실수 타입으로
print(b.shape)
print(b)

tensor([1, 2, 3, 4])
<class 'torch.Tensor'>
torch.int64
torch.Size([4])
tensor([1, 2, 3, 4])
torch.float32
torch.Size([4])
tensor([1.0000, 2.0000, 3.1000, 4.0000])


In [ ]:
A=torch.tensor([[1,2,3],[3,4,5]])
# A=torch.tensor([[1,2],[3,4,5]]) # 리스트와는 달리 이제는 행렬이라서 각 행에 해당하는 숫자의 개수가 같아야 함
print(A)
print(A.shape) # 2행 3열
print(A.ndim) # 차원의 수 바깥의 괄호 수가 차원을 나타냄
print(A.size)
print(A.numel()) # 전체 성분의 수

tensor([[1, 2, 3],
        [3, 4, 5]])
torch.Size([2, 3])
2
<built-in method size of Tensor object at 0x7867a868f420>
6


In [ ]:
print(torch.zeros(5))
print(torch.zeros(5).dtype)
print(torch.zeros_like(A))
print(torch.ones(5))
print(torch.zeros( (3,3) )) # 튜플을 입력으로! 그냥 np.zeros(3,3)은 안돼요
print(torch.arange(3,10,2)) # range랑 같은데 array로 만들어줌
print(torch.arange(0,1,0.1)) # 소수점 가능 마지막 포함 안한다
print(torch.linspace(0,1,10)) # 0 에서부터 1 포함(default) 10개로

tensor([0., 0., 0., 0., 0.])
torch.float32
tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([1., 1., 1., 1., 1.])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([3, 5, 7, 9])
tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000])
tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000])


In [ ]:
a=torch.tensor([1,2,3]) #1d tensor는 행렬이라고 하지 않는다
b=torch.tensor([4,5,6])
c=a+b
print(c) # 드디어! 양 옆으로 길어지는 게 아닌 벡터의 합이 나옴! 리스트는 길어진다

tensor([5, 7, 9])


In [ ]:
A=torch.tensor([[1,2,3],[1,2,3]])
B=torch.tensor([[4,5,6],[1,1,1]])
C=A+B
D=A-B
print(C)
print(D)
print()
print(A*B) # 곱셈은? 성분끼리의 곱! (Hadamard product) 그래서 2 by 3도 가능하다
print(A/B) # 나누기도 마찬가지
print(B**2) # 제곱도 각 성분에 대해서 해준다

tensor([[5, 7, 9],
        [2, 3, 4]])
tensor([[-3, -3, -3],
        [ 0,  1,  2]])

tensor([[ 4, 10, 18],
        [ 1,  2,  3]])
tensor([[0.2500, 0.4000, 0.5000],
        [1.0000, 2.0000, 3.0000]])
tensor([[16, 25, 36],
        [ 1,  1,  1]])


In [ ]:
A=torch.tensor([[1,2],[3,4]])
B=torch.tensor([[1,2],[3,4]])
print(A*B)
print(A@B) # 이게 진짜 행렬 곱하기

tensor([[ 1,  4],
        [ 9, 16]])
tensor([[ 7, 10],
        [15, 22]])


## pytorch 의 인덱싱 슬라이스

In [ ]:
a=torch.tensor([1,2,3,4,5,6,7,8,9])
# 인덱싱과 슬라이싱, list할 때와 동일!
print(a[0])
print(a[1])
print(a[-1]) # 맨 마지막
print(a[1:4]) # 1번째부터 3번째까지
print(a[7:]) # 7번째부터 마지막까지
print(a[:7]) # 처음부터 6번째까지
print(a[:]) # 전체

tensor(1)
tensor(2)
tensor(9)
tensor([2, 3, 4])
tensor([8, 9])
tensor([1, 2, 3, 4, 5, 6, 7])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [ ]:
# 행렬에 대한 인덱싱과 슬라이싱
A=torch.tensor([[1,2,3],[4,5,6],[7,8,9]]) # 3 by 3
print(A[0]) # 하나만 쓰면 행에 대한 인덱싱 (리스트 속 리스트 생각)
print(A[-1])
print(A[1:]) # 1번째 행부터 마지막까지
print(A[:])
print(A[0][2])
print(A[0,2]) # 2차원 행렬도 동일한데, 리스트와 달리 이런 것도 됨
print(A[1,:]) # 1 행, 전부
print(A[1,0:3:2]) # 0부터 3미만번째 2간격 즉 0,2
print(A[:,2]) # 전부, 2 열
print(A[:][2]) # 이거는 다른 표현
print()
B=[[1,2,3,4], [5,6,7,8]] # 일반 리스트
print(B)
print(B[0][2])
# print(B[0,2]) # error!

tensor([1, 2, 3])
tensor([7, 8, 9])
tensor([[4, 5, 6],
        [7, 8, 9]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor(3)
tensor(3)
tensor([4, 5, 6])
tensor([4, 6])
tensor([3, 6, 9])
tensor([7, 8, 9])

[[1, 2, 3, 4], [5, 6, 7, 8]]
3


In [ ]:
# 3차원 행렬 인덱싱
A=torch.tensor([ [[0,1,2,3],[4,5,6,7],[8,9,10,11]] ,
             [[12,13,14,15],[16,17,18,19],[20,21,22,23]] ]) # 3행 4열 짜리 두개 : 3차원
print(A)
print(A.shape) # 대괄호가 하나 늘어나면 왼쪽에 shape 값이 추가 된다. [2,3,4] 3 by 4 2개
print(A[0,1,2]) # [채널, 행, 열]

a=torch.tensor([[[1,2,3,4]]])
print(a.shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
torch.Size([2, 3, 4])
tensor(6)
torch.Size([1, 1, 4])


In [ ]:
# boolean 인덱싱
a=[1,2,3,4,5,3,3]
print(a==3) # 여러개 값 들어있는 리스트랑 3 달랑 하나랑 같냐? 다르다!
A=torch.tensor([[1,2,3,4],[5,3,7,3]])
print(A==3) # 리스트와 달리 각 성분에 대해 비교해줌, 그래서 모든 원소 참 거짓이 출력된다
print(A[A==3]) # True, False가 담긴 행렬로 인덱싱 가능!!
A[A==3] = 100
print(A) # 그러면 이런 것도 가능하다! (3과 같은 애를 100으로 바꿔줘)

A=torch.tensor([[1,2],[3,4],[5,6],[7,8]])
B=torch.tensor([True, False, False, True]) # 참고로 그냥 리스트여도 됨
print(A[B,:]) # 0행, 3행 슬라이싱, true 가 박혀있는 행을 가져온다

b=torch.tensor([1,2,3,4])
print(b[[True,True,False,False]]) # bool 이 torch tensor가 아니어도 된다
c=[1,2,3,4]
# c[[True,True,False,False]] # error!

False
tensor([[False, False,  True, False],
        [False,  True, False,  True]])
tensor([3, 3, 3])
tensor([[  1,   2, 100,   4],
        [  5, 100,   7, 100]])
tensor([[1, 2],
        [7, 8]])
tensor([1, 2])


In [ ]:
# tensor로 인덱싱
a=torch.tensor([1,2,3,4,5])
A=a[2]
print(A) # tensor(3)
A=a[ torch.tensor(2) ] # torch.tensor 안에다가? torch tensor 로 인덱싱
print(A)
A=a[ torch.tensor([2,3,4]) ]
print(A)
A=a[ torch.tensor([[2,2,2],[3,3,3]]) ]
print(A) # 인덱싱된 애들로 2행 3열짜리 행렬을 만든다

a=[1,2,3]
# a[ [1,1,1,1,2,2,2] ] # error! 리스트로는 안된다

a= torch.tensor([[1,2,3],[4,5,6]])
print(a[0])
A=a[ torch.tensor([[0,1],[1,1]]) ]
print(A.shape) # 예를 들어, a[0] = array([1,2,3])과 같이 1차원 데이터이므로 한 차원이 뒤에 늘어나서 2,2, "3" 이 된다!
print(A) # segmentation 결과 그림 보여줄 때 사용!
print(A.size()) # Shape 랑 size() 는 똑같다

tensor(3)
tensor(3)
tensor([3, 4, 5])
tensor([[3, 3, 3],
        [4, 4, 4]])
tensor([1, 2, 3])
tensor([2, 5])
torch.Size([2, 2, 3])
tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[4, 5, 6],
         [4, 5, 6]]])
torch.Size([2, 2, 3])


In [ ]:
A=torch.tensor([[1,2],[3,4],[5,6],[7,8]])
print(A)
print(A.shape)

# 1. A[몇 번째 행이냐, 몇 번째 열이냐]
print(A[0,1])
# 2. A[ tensor(bool) ] => A와 같은 shape을 가지는 tensor bool이 어디에 True를 가지고 있냐
print(A[ torch.tensor([[False,True],[True,True],[False,False],[False,False]]) ])
print()
print(A[A==2])
print()
# 3. A[몇 번째 값에 True가 있냐, 몇 번째 값에 True가 있냐]
print(A[ [True,False,False,True], [False,True] ])
# 4. A[ tensor ] # 몇 번째 것을 어떻게 쌓을거냐
print(A[ torch.tensor([1,1,2,2,2]) ])

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
torch.Size([4, 2])
tensor(2)
tensor([2, 3, 4])

tensor([2])

tensor([2, 8])
tensor([[3, 4],
        [3, 4],
        [5, 6],
        [5, 6],
        [5, 6]])


## pytorch의 여러 함수들

In [15]:
A=torch.randn(3,3) # 여긴 튜플로 안줘도 됨 3행 3열짜리 0과 1사이에 평균 0, 분산 1 정규분포에 따라
# 곱하면 분산이 바뀌고 더하면 평균이 바뀐다.
B=torch.rand(3,3) # 여긴 튜플로 안줘도 됨 3행 3열짜리 0과 1사이에 균등분포(uniform)에 따라
print(A)
print(B)
print(A[A[:,0]<0,:]) # 행이 박힌 다음 모든 열을 출력

tensor([[ 0.0181, -2.3493, -0.8805],
        [-0.4624,  0.4776, -0.1686],
        [-0.0952,  0.9685, -1.1741]])
tensor([[0.8667, 0.8274, 0.5715],
        [0.0708, 0.9927, 0.2944],
        [0.7093, 0.6061, 0.4261]])
tensor([[-0.4624,  0.4776, -0.1686],
        [-0.0952,  0.9685, -1.1741]])


In [27]:
A=torch.randn(3,3)
print(A)
print(torch.abs(A))
print(torch.sqrt(torch.abs(A)))
print(torch.exp(A))
print(torch.log(torch.abs(A)))
print(torch.log(torch.exp(torch.tensor(1)))) # 기본 torch.log 의 밑은 e이다
print(torch.log10(torch.tensor(10))) # 밑을 따로 지정
print(torch.log2(torch.tensor(2)))
print(torch.round(A)) # 반올림
print(torch.round(A,decimals=2)) # 소수점 둘째자리까지
print(torch.floor(A)) # 내림
print(torch.ceil(A)) # 올림

tensor([[-0.4435,  1.2068,  0.2651],
        [ 1.2006,  0.4480, -1.2392],
        [-0.3374,  1.2980,  1.2362]])
tensor([[0.4435, 1.2068, 0.2651],
        [1.2006, 0.4480, 1.2392],
        [0.3374, 1.2980, 1.2362]])
tensor([[0.6660, 1.0986, 0.5149],
        [1.0957, 0.6693, 1.1132],
        [0.5808, 1.1393, 1.1119]])
tensor([[0.6418, 3.3429, 1.3036],
        [3.3222, 1.5652, 0.2896],
        [0.7137, 3.6620, 3.4426]])
tensor([[-0.8131,  0.1880, -1.3275],
        [ 0.1828, -0.8029,  0.2144],
        [-1.0866,  0.2608,  0.2121]])
tensor(1.)
tensor(1.)
tensor(1.)
tensor([[-0.,  1.,  0.],
        [ 1.,  0., -1.],
        [-0.,  1.,  1.]])
tensor([[-0.4400,  1.2100,  0.2700],
        [ 1.2000,  0.4500, -1.2400],
        [-0.3400,  1.3000,  1.2400]])
tensor([[-1.,  1.,  0.],
        [ 1.,  0., -2.],
        [-1.,  1.,  1.]])
tensor([[-0.,  2.,  1.],
        [ 2.,  1., -1.],
        [-0.,  2.,  2.]])


In [29]:
print(torch.sin(torch.tensor(torch.pi/6)))
print(torch.cos(torch.tensor(torch.pi/3)))
print(torch.tan(torch.tensor(torch.pi/4)))
print(torch.tanh(torch.tensor(-10)))

tensor(0.5000)
tensor(0.5000)
tensor(1.)
tensor(-1.)


In [30]:
torch.nan # not a number
print(torch.isnan(torch.tensor([1,2,torch.nan,3,4]))) # nan이 있는지 없는지
print(torch.isinf(torch.tensor([1,2,3,4,torch.inf])))

tensor([False, False,  True, False, False])
tensor([False, False, False, False,  True])


In [36]:
A=torch.randn(3,4)
print(A)
print(torch.max(A)) # 가장 큰 값만 나옴
print(torch.max(A,dim=0)) # dim까지 써주면 인덱스까지 리턴, 행끼리 비교
print()
print(torch.max(A,dim=1)) # 1D array로 바꿔버림, 열끼리 비교
print(torch.max(A,dim=0, keepdims=True))
print(torch.max(A,dim=1, keepdims=True)) # 3 행 1열 짜리 2D array
print(torch.min(A))
print(torch.min(A,dim=0))
print(torch.min(A,dim=1))
print(torch.argmax(A)) # 가장 큰 놈의 인덱스를 뱉어라 ex)0~10
print(torch.argmax(A,dim=0)) # 각 열에서 가장 큰 애가 존재하는 인덱스
print(torch.argmax(A,dim=1)) # 각 행에서 가장 큰 애가 존재하는 인덱스

tensor([[ 1.6149,  0.2171,  1.3518, -0.9073],
        [-0.0726,  1.1452, -0.4244,  0.5735],
        [-2.1336, -1.1514,  0.2474,  0.1787]])
tensor(1.6149)
torch.return_types.max(
values=tensor([1.6149, 1.1452, 1.3518, 0.5735]),
indices=tensor([0, 1, 0, 1]))

torch.return_types.max(
values=tensor([1.6149, 1.1452, 0.2474]),
indices=tensor([0, 1, 2]))
torch.return_types.max(
values=tensor([[1.6149, 1.1452, 1.3518, 0.5735]]),
indices=tensor([[0, 1, 0, 1]]))
torch.return_types.max(
values=tensor([[1.6149],
        [1.1452],
        [0.2474]]),
indices=tensor([[0],
        [1],
        [2]]))
tensor(-2.1336)
torch.return_types.min(
values=tensor([-2.1336, -1.1514, -0.4244, -0.9073]),
indices=tensor([2, 2, 1, 0]))
torch.return_types.min(
values=tensor([-0.9073, -0.4244, -2.1336]),
indices=tensor([3, 2, 0]))
tensor(0)
tensor([0, 1, 0, 1])
tensor([0, 1, 2])


In [47]:
a=torch.randn(6,1)
print(a)
a_sorted=torch.sort(a,dim=0) # 기본 오름차순
print(a_sorted)
a_sorted=torch.sort(a,dim=0,descending=True) # 내림차순
print(a_sorted)
print(a.sort(dim=0))
print(a.max())
print(torch.argmax(a))

tensor([[ 1.6213],
        [ 0.4827],
        [-1.0798],
        [ 0.9387],
        [ 0.3514],
        [-0.7336]])
torch.return_types.sort(
values=tensor([[-1.0798],
        [-0.7336],
        [ 0.3514],
        [ 0.4827],
        [ 0.9387],
        [ 1.6213]]),
indices=tensor([[2],
        [5],
        [4],
        [1],
        [3],
        [0]]))
torch.return_types.sort(
values=tensor([[ 1.6213],
        [ 0.9387],
        [ 0.4827],
        [ 0.3514],
        [-0.7336],
        [-1.0798]]),
indices=tensor([[0],
        [3],
        [1],
        [4],
        [5],
        [2]]))
torch.return_types.sort(
values=tensor([[-1.0798],
        [-0.7336],
        [ 0.3514],
        [ 0.4827],
        [ 0.9387],
        [ 1.6213]]),
indices=tensor([[2],
        [5],
        [4],
        [1],
        [3],
        [0]]))
tensor(1.6213)
tensor(0)


In [49]:
A=torch.randn(3,4)
print(A)
print(torch.sum(A))
print(torch.sum(A,dim=0))
print(torch.sum(A,dim=1))
print(torch.sum(A,dim=0,keepdims=True)) # dimesion을 유지해달라
print(torch.sum(A,dim=1,keepdims=True)) # dimesion을 유지해달라 shape이 맞춰진다
print(torch.mean(A))
print(torch.mean(A,dim=1))
print(torch.mean(A,dim=1,keepdims=True))
print(torch.std(A)) # standard deviation 표준 편차

print(A.sum(dim=1, keepdims=True))
print(A.mean(dim=1, keepdims=True))
print(A.std())

tensor([[ 0.6258,  0.1942,  0.9174, -0.4516],
        [-0.7273,  0.5736, -0.9398,  1.0399],
        [-0.0180, -0.3654,  0.1104, -0.4740]])
tensor(0.4852)
tensor([-0.1195,  0.4025,  0.0880,  0.1142])
tensor([ 1.2858, -0.0536, -0.7469])
tensor([[-0.1195,  0.4025,  0.0880,  0.1142]])
tensor([[ 1.2858],
        [-0.0536],
        [-0.7469]])
tensor(0.0404)
tensor([ 0.3214, -0.0134, -0.1867])
tensor([[ 0.3214],
        [-0.0134],
        [-0.1867]])
tensor(0.6501)
tensor([[ 1.2858],
        [-0.0536],
        [-0.7469]])
tensor([[ 0.3214],
        [-0.0134],
        [-0.1867]])
tensor(0.6501)


In [54]:
A=torch.randint(1,5,size=(12,)) # 1부터 5미만 12개 정수 (1 차원은 (N,) 과 같이 표현)
print(A)
print(A.shape)

B=A.reshape(2,2,3) # 중요
print(B)
print(B.ndim) # 3 차원 행렬이다

tensor([3, 2, 4, 2, 4, 3, 3, 1, 1, 1, 2, 3])
torch.Size([12])
tensor([[[3, 2, 4],
         [2, 4, 3]],

        [[3, 1, 1],
         [1, 2, 3]]])
3


In [60]:
a=torch.tensor([1,2,3])
b=torch.tensor([2,2,1])
print(torch.sum(a*b))

a=a.reshape(3,1)
b=b.reshape(3,1)
print(a.transpose(1,0)@b)
print(a.permute(1,0)@b)
print(a.T@b)
print(a.t()@b)

A=torch.randn(4,3,6)
print(A.permute(0,2,1).shape)

tensor(9)
tensor([[9]])
tensor([[9]])
tensor([[9]])
tensor([[9]])
torch.Size([4, 6, 3])


In [63]:
A=torch.arange(20)
print(A)
print(A.reshape(4,5))
print(A.reshape(4,-1).shape) # 4개 행이 될 수 있도록 알아서 열의 수를 맞춰라
print(A.reshape(2,5,-1).shape)
print(A.reshape(2,-1,5).shape)
print(A.reshape(1,-1).shape) # 2차원 행 벡터
print(A.reshape(-1,1).shape) # 2차원 열 벡터

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])
tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])
torch.Size([4, 5])
torch.Size([2, 5, 2])
torch.Size([2, 2, 5])
torch.Size([1, 20])
torch.Size([20, 1])


In [66]:
x=torch.randn(2,3,4,5,6)
print(x[1,2,:,:,:].shape)
print(x[1,2,...].shape) # x[1, 2, …] 는 x[1, 2, :, :, :] 와 같습니다.
print(x[:,:,:,:,3].shape)
print(x[...,3].shape) # x[…, 3] 는 x[:, :, :, :, 3] 와 같습니다.
print(x[1,:,:,3,:].shape)
print(x[1,...,3,:].shape) # x[1, …, 3, :] 는 x[1, :, :, 3, :] 와 같습니다.

torch.Size([4, 5, 6])
torch.Size([4, 5, 6])
torch.Size([2, 3, 4, 5])
torch.Size([2, 3, 4, 5])
torch.Size([3, 4, 6])
torch.Size([3, 4, 6])


In [78]:
A=torch.ones((2,3,4))
B=torch.zeros((2,3,4))

C=torch.vstack([A,B]) # dim=0에 대해서 쌓는다
D=torch.hstack([A,B]) # dim=1에 대해서 쌓는다

E=torch.cat([A,B], dim=0)
F=torch.cat([A,B], dim=1)
G=torch.cat([A,B], dim=2)

print(C.shape)
print(D.shape)
print(E.shape)
print(F.shape)
print(G.shape)

torch.Size([4, 3, 4])
torch.Size([2, 6, 4])
torch.Size([4, 3, 4])
torch.Size([2, 6, 4])
torch.Size([2, 3, 8])


In [83]:
A = torch.randn(1,1,1,3,1,1,4,1)
# print(A)
print(A.shape)
print(A.squeeze().shape) # 쥐어짜서 1짜리를 없앤다

torch.Size([1, 1, 1, 3, 1, 1, 4, 1])
torch.Size([3, 4])


In [87]:
A=torch.randn(3,4)
print(A.unsqueeze(dim=0).shape) # 차원을 하나 늘린다
print(A.unsqueeze(dim=1).shape)
print(A.unsqueeze(dim=2).shape)
print(A.reshape(1,3,4).shape)
print(A.reshape(3,1,4).shape)
print(A.reshape(3,4,1).shape)

torch.Size([1, 3, 4])
torch.Size([3, 1, 4])
torch.Size([3, 4, 1])
torch.Size([1, 3, 4])
torch.Size([3, 1, 4])
torch.Size([3, 4, 1])


In [90]:
A=torch.ones(3,4)
B=torch.zeros(3,4)
print(A)
print(B)
A=A.unsqueeze(dim=0)
B=B.unsqueeze(dim=0)
C=torch.cat([A,B],dim=0)
print(C)
print(C.shape)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
torch.Size([2, 3, 4])


In [92]:
A=torch.tensor([[1,2],[3,4]])
B=A.clone() # 그냥 B=A 하면 주소가 복사된다
B[0,0]=100

print(B)
print(A)

tensor([[100,   2],
        [  3,   4]])
tensor([[1, 2],
        [3, 4]])
